# language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t andrewklim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andrewklim/docker-react yarn test
